receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        cors:
          allowed_origins:
            - "*"
          allowed_headers:
            - "*"

  # Prometheus metrics receiver (optional)
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['0.0.0.0:8888']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Resource processor to add/modify resource attributes
  resource:
    attributes:
      - key: service.instance.id
        value: "otel-collector"
        action: upsert
      - key: deployment.environment
        value: "development"
        action: upsert

  # Memory limiter
  memory_limiter:
    limit_mib: 512

exporters:
  # Export traces to Tempo
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Export logs to Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    tenant_id: "otel"
    labels:
      attributes:
        service.name: "service_name"
        service.instance.id: "service_instance_id"
      resource:
        container.name: "container_name"
        k8s.pod.name: "k8s_pod_name"

  # Export metrics to Prometheus (remote write - optional)
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true

  # Prometheus metrics exporter (for collector internal metrics)
  prometheus:
    endpoint: "0.0.0.0:8888"
    const_labels:
      service: "otel-collector"

  # Debug exporter (for development)
  logging:
    loglevel: debug

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [prometheus, prometheusremotewrite]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, batch]
      exporters: [loki]

  extensions: []

  telemetry:
    logs:
      level: "info"
    metrics:
      address: 0.0.0.0:8888
